---
- include_tasks: read-configs.yml
- include_tasks: sourcepath.yml

- debug:
    msg: |
      List files in backup, user: '{{ username }}', profile: '{{ profile_name }}'
      Backup location: {{ remote.backup_location }}"
      Age: {{ age }}

# Using `sudo` like on the command line works, using `become` fails

- block:
    - name: List files in backup from file system
      command: "sudo -E duply {{ profile_path|quote }} list {{ age|quote }}"
      register: duply
      failed_when: duply.stdout is search("Errno") or duply.rc > 0
    - debug:
        var: duply.stdout
  when: remote.backup_location is match('^file:///')

- block:
    - name: List files in backup from S3 storage
      command: "sudo -E duply {{ profile_path|quote }} list {{ age|quote }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{ remote.api_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ remote.api_key_secret }}"
      register: duply
      failed_when: duply.stdout is search("Errno") or duply.rc > 0
    - debug:
        var: duply.stdout
  when: remote.backup_location is match('^s3://')

# Add more `list` setups here
