---
- name: Remove the user '{{ username }}'
  user:
    name: "{{ username }}"
    state: absent
    remove: yes
  register: result
  become: yes

# not explicitly deleting primary group. system should take care of it
