---
- name: Remove the user {{ username }}
  user:
    name: "{{ username }}"
    state: absent
    remove: yes
  register: result
  become: yes

- debug:
    msg: no user was removed. ending play.
  when: not result.changed

- meta: end_play
  when: not result.changed

- name: Delete user "{{ username}}" from users config
  dict_element_delete:
    dict: "{{ config | from_yaml }}"
    key: "{{ username }}"
  register: result

- name: "Overwrite config var"
  set_fact:
    config: "{{ result.dict }}"

- name:  write updated users config
  import_role:
    name: common
    tasks_from: write-config
