---
- name: Remove the user '{{ username }}'
  user:
    name: "{{ username }}"
    state: absent
    remove: yes
  register: result
  become: yes

- debug:
    msg: no user was removed. ending play.
  when: not result.changed

- meta: end_play
  when: not result.changed
