---


- name: Add the 'khoe' user to 'plugdev' group.
  user:
    name: khoe
    groups: plugdev
    append: yes
  become: yes
  become_user: root
  tags: [ 'never', 'install' ]


- name: Add Universe repository
  apt_repository:
    repo: deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} universe
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
  tags: [ 'never', 'install' ]


- name: Install pmount.
  apt:
    name: pmount
    state: present
  tags: [ 'never', 'install' ]


- import_role:
    name: common
    tasks_from: install-config
  vars:
    file: mounts.yml
  tags: [ 'never', 'install' ]


- import_role:
    name: common
    tasks_from: load-config
  vars:
    file: mounts.yml


- include_tasks: mount.yml
  loop: "{{ config | list }}"
