---
- name: "Check if disk is mounted: {{ item.key }}"
  shell: pmount | grep {{ item.key }}
  register: grep
  failed_when: "grep.rc == 2"
  check_mode: no
  changed_when: false

- debug:
    msg: "Disk {{ item.key }} is already mounted."
  when: grep.rc == 0


- block:

    - name: "Ensure mount dir is absent before mounting"
      file:
        path: "/media/{{ item.key }}"
        state: absent

    - name: "Mount disk {{ item.key }} to /media/{{ item.key }}."
      shell: pmount /dev/disk/by-label/{{ item.key }} {{ item.key }}

  when: grep.rc == 1
