---
- name: "Check if disk is mounted: {{ item.key|quote }}"
  shell: 'pmount | grep {{ item.key|quote }}'
  register: grep
  failed_when: "grep.rc == 2"
  check_mode: no
  changed_when: false

- debug:
    msg: "Disk is already mounted: {{ item.key|quote }}"
  when: grep.rc == 0

- block:

    - name: 'Ensure mount dir is absent before mounting: {{ mount_path|quote }}'
      file:
        path: '{{ mount_path|quote }}'
        state: absent
      become: yes

    - name: "Mount disk, label: {{ disk_path|quote }}, mount path: {{ mount_path|quote }}."
      command: 'pmount {{ disk_path|quote }} {{ item.key|quote }}'

  when: grep.rc == 1
