---
# - setup:
#     gather_subset:
#       - hardware

# Get CPU architecture (faster)
- name: 'Get DEB architecture.'
  command: dpkg --print-architecture
  changed_when: false
  register: deb_arch_cmd

- set_fact:
    deb_architecture: '{{deb_arch_cmd.stdout}}'
- set_fact:
    architecture_is_arm: '{{ deb_architecture is search("arm") | ternary(true, false) }}'
