---
# usage ansible-playbook playbooks/gpg.yml -e task=delete -e username=khoe [-e fingerprint=9409A43E4F16771D8FBF25CADF8D04072F675974]

- name: "Read fingerprint from file: {{ fingerprint_path }}"
  command: "cat {{ fingerprint_path }}"
  register: fingerprint
  changed_when: false
  when: fingerprint is not defined

- name: "Set fingerprint var"
  set_fact:
    fingerprint: "{{ fingerprint.stdout }}"
  when: fingerprint.stdout is defined

- name: "Deleting key with fingerprint {{ fingerprint }} for user: {{ username }}."
  command: "gpg2 --batch --yes --delete-secret-and-public-key {{ fingerprint }}"
  register: gpg_output
  become: yes
  become_user: "{{ username }}"

- name: "Delete fingerprint file from /home/{{ username }}."
  file:
    state: absent
    path: "{{ fingerprint_path }}"
    owner: "{{ username }}"
    group: khoe
  become: yes
  become_user: "{{ username }}"

# to do: store / remove fingerprint in user config?
