---
- name: "Check that a home directory exists for the username: {{ username }}."
  stat:
    path: "/home/{{ username }}"
  register: stat_result
  failed_when: stat_result.stat.isdir is not defined or stat_result.stat.isdir == False

- name: "Ensure export directory exists: {{ export_path }}."
  file:
    path: "{{ export_path }}"
    state: directory
    mode: 0700

- name: "Export secret key '{{ username }}' to: {{ export_key_file }}." # gpg secret key contains public key
  shell: "echo '{{ passphrase | default(omit) }}' | gpg2 --batch --passphrase-fd 0 --pinentry-mode loopback --armor --export-secret-keys {{ username }} > {{ export_key_file }}"

- name: "Export ownertrust to: {{ export_ownertrust_file }}"
  shell: "gpg2 --export-ownertrust > {{ export_ownertrust_file }}"

- name: "Restrict permissions on exported files: {{ export_path }}."
  file:
    path: "{{ item }}"
    mode: 0600
  with_items:
    - "{{ export_ownertrust_file }}"
    - "{{ export_key_file }}"
