---
# manual backup run: `duply /home/khoe/.duply/[profile_name] backup` as root after creating profile using this role

- hosts: khoe
  gather_facts: no

  become: yes # oefenweb.duply is written to require root
  become_user: root

  tasks:

    - set_fact: profile_name=nas # no quotes, no comma; otherwise it will be part of the string value
    - set_fact: user_name="khoe"
    - set_fact: source_path="/home/{{ user_name }}"
    - set_fact: target_path="file:///home/{{ user_name }}/_backup/{{ profile_name }}"

    - include_role:
        name: oefenweb.duply-backup
      vars:
        duply_backup_profile_directory: "/home/{{ user_name }}/.duply" # default set by oefenweb.duply: `/etc/duply/[profile_name]`
        duply_backup_profiles:
          '{{ profile_name }}':
            conf:
              # gpg_key: 'E6564C6E'
              # gpg_pw: 'QUsNMnD6GHUTFSBruSwbJpZBhto='
              # gpg_key_sign: 'E79C7756'
              # gpg_pw_sign: 'QUsNMnD6GHUTFSBruSwbJpZBhto='

              source: "{{ source_path }}"
              target: "{{ target_path }}"

              # max_age: 1W
              # max_fullbkp_age: 1M

              #verbosity: 5

              #arch_dir: '/data/backup/.duply-cache'
            # pre: ../../../files/duply-backup/pre
            # post: ../../../files/duply-backup/post
            excludes:
              - '+ {{ source_path }}/nas'
              - '- **'

        # duply_backup_gpg_pub_keys:
        #   - ../../../files/duply-backup/E6564C6E.pub.asc
        # duply_backup_gpg_ownertrusts:
        #   - ../../../files/duply-backup/E6564C6E.ownertrust.txt
        # duply_backup_gpg_sec_keys:
        #   - ../../../files/duply-backup/E6564C6E.sec.asc
        # duply_backup_jobs:
        #   - name: duply-backup-etc
        #     job: /usr/local/bin/duply etc backup
        #     minute: "0"
